Controllers/BookController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System;
using System.Web.Mvc;
using BookStore.Models;
using System.Data.Entity;

namespace BookStore.Controllers
{
    [Authorize(Roles = "admin")]
    public class BookController : Controller
    {

        BookContext db = new BookContext();

        public ActionResult Index()
        {

            var books = db.Books.Include(p => p.Genre).Include(p => p.Country).Include(p => p.Language).Include(p => p.Cover);


            return View(books.ToList());
        }
        [HttpGet]
        public ActionResult EditBook(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Book book = db.Books.Find(id);
            if (book != null)
            {
                SelectList genres = new SelectList(db.Genres, "Id", "GenreName", book.GenreId);
                ViewBag.Genres = genres;
                SelectList countries = new SelectList(db.Countries, "Id", "CountryName", book.CountryId);
                ViewBag.Countries = countries;
                SelectList languages = new SelectList(db.Languages, "Id", "LanguageName", book.LanguageId);
                ViewBag.Languages = languages;
                SelectList covers = new SelectList(db.Covers, "Id", "CoverName", book.CoverId);
                ViewBag.Covers = covers;
                return View(book);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
            }

            return RedirectToAction("EditBook") ;
        }
        [HttpGet]
        public ActionResult Create()
        {
            SelectList genres = new SelectList(db.Genres, "Id", "GenreName");
            ViewBag.Genres = genres;
            SelectList countries = new SelectList(db.Countries, "Id", "CountryName");
            ViewBag.Countries = countries;
            SelectList languages = new SelectList(db.Languages, "Id", "LanguageName");
            ViewBag.Languages = languages;
            SelectList covers = new SelectList(db.Covers, "Id", "CoverName");
            ViewBag.Covers = covers;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Create");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            
            Book b = db.Books.Find(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            
            return View(b);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Book b = db.Books.Find(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            db.Books.Remove(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/PurchaseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System;
using System.Web.Mvc;
using BookStore.Models;
using System.Data.Entity;

namespace BookStore.Controllers
{
    [Authorize(Roles = "admin")]
    public class PurchaseController : Controller
    {
        BookContext db = new BookContext();
        public ActionResult Index(int? bookId, string person)
        {
            IQueryable<Purchase> purchases = db.Purchases;
            if (bookId != null && bookId != 0)
            {
                purchases = purchases.Where(p => p.BookId == bookId);
            }
            if (!String.IsNullOrEmpty(person) && !person.Equals("Все"))
            {
                purchases = purchases.Where(p => p.Person == person);
            }
            List<int> bookIds = db.Purchases.Select(p => p.BookId).Distinct().ToList();
            bookIds.Insert(0, 0);
            List<string> persons = db.Purchases.Select(p => p.Person).Distinct().ToList();
            persons.Insert(0, "Все");
            BooksListViewModel blvm = new BooksListViewModel
            {
                Purchases = purchases.ToList(),
                BookIds = new SelectList(bookIds),
                Persons = new SelectList(persons)
                
            };
            return View(blvm);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <div class="container">
        <nav>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Редактировать", "Index", "Book")</li>
                    <li>@Html.ActionLink("Заказы", "Index", "Purchase")</li>
                    <li>@Html.ActionLink("Выход", "Logout", "Account")</li>

                </ul>
            </div>
            </nav>
                @RenderBody()
</div>



</body>

</html>